name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Set up Configuration
        run: |
          echo "{\"Jwt\":{\"SecretKey\":\"${{ secrets.JWT_SECRET_KEY }}\",\"Issuer\":\"${{ secrets.JWT_ISSUER }}\",\"Audience\":\"${{ secrets.JWT_AUDIENCE }}\"}}" > appsettings.json

      - name: Test
        run: dotnet test --no-build --verbosity normal
